title: Site

columns:
  - width: 2/3
    sections:
      albums: sections/projects
  - width: 1/3
    sections:
      pages:
        type: pages
        create: default
        max: 1
        template:
          - about
          - home
          - default
